version: '3'
services:
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"

  mailhog:
    image: jcalonso/mailhog
    restart: always
    ports:
      - "8025:8025"
  litecart:
    container_name: litecart
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./lc_base:/lc_base
      - ./lc_digitals:/lc_digitals
      - ./lc_uploads:/lc_uploads
      - ./site:/site
    image: shurco/litecart:latest
